version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: flask-bd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql